### ISSUE TITLE
"...failed to create file at %dotFetchDirectory%" when attempting to screenshot

### ISSUE THREAD

**Issue by 4naxagoras** [lavjamanxd/DotFetch#1]
![untitled](https://cloud.githubusercontent.com/assets/13698095/9142303/27fc2f50-3d15-11e5-88e2-37beef0bb136.png)

On Windows 10 Enterprise N LSTB x64
Running as admin changes nothing

**Comment by lavjamanxd** [comment]
ah, thanks for the report+screenshot, i already tried to fix this issue, but i didn't know what causing this issue.
but now i figured out where's the problem, i'll fix soon :smile:

**Comment by 4naxagoras** [comment]
Can confirm it's fixed. Thank you!
